#!/usr/bin/env bash
#
# Sets up the user's environment to run EPI2ME workflows on the CHPC.
#
# To perform said setup, source this script; i.e., issue this command:
#   source /absolute/path/to/ewtrc
# To have it performed at login, add said command to your $HOME/.bashrc file
#   (at your own risk; typically to the end of it).
#
# Only the values of the EWT_HOME and NXF_{HOME,WORK,SINGULARITY_CACHEDIR}
#   environment variables are respected if already set, though said values must
#   still each point to a location on an appropriate filesystem.

_ewtrc_derive_dirname() {
  local full_path
  full_path="$(realpath "$1" 2>/dev/null)" || {
    ((_ewtrc_verbose)) && echo >&2 "ERROR: Unable to resolve realpath for $1."
    return 3
  }
  echo "${full_path%/*}"
}

_ewtrc_cleanup() {
  unset -v _all_safe var _on_user_lustre_{or_home,only}
  unset -f _ewtrc_cleanup
}
trap _ewtrc_cleanup RETURN

_on_user_lustre_or_home=(EWT_HOME NXF_HOME)
_on_user_lustre_only=(NXF_WORK NXF_SINGULARITY_CACHEDIR)

[[ -v PBS_ENVIRONMENT || ! $- =~ "i" ]] && _ewtrc_verbose=0 || _ewtrc_verbose=1
export _ewtrc_verbose

[[ ${BASH_SOURCE[0]} != "$0" ]] || {
  ((_ewtrc_verbose)) && echo >&2 "ERROR: ${BASH_SOURCE[0]} can only be sourced."
  exit 1
}

[[ -v EWT_HOME ]] || EWT_HOME=$(_ewtrc_derive_dirname "${BASH_SOURCE[0]}") || {
  ((_ewtrc_verbose)) && echo >&2 "ERROR: Unable to resolve EWT_HOME."
  return 3
}

export USER_LUSTRE=/mnt/lustre/users/$USER

# NOTE:   The fallbacks for NXF_{WORK,SING*} are on lustre to protect $HOME from
#           heavy I/O loads.
# NB:     This fallback for NXF_WORK should not be treated as a default!
#           None of the tools that this package provides are designed to use
#           a monolithic NXF_WORK directory like this.
: "${NXF_HOME:=$HOME/.nextflow}"
: "${NXF_WORK:=$USER_LUSTRE/nextflow_work}"
: "${NXF_SINGULARITY_CACHEDIR:=$USER_LUSTRE/singularity_cache}"

_all_safe=1
for var in "${_on_user_lustre_or_home[@]}"; do
  [[ ${!var} == $HOME/* || ${!var} == $USER_LUSTRE/* ]] || {
    ((_ewtrc_verbose)) && {
      echo >&2 "ERROR: $var must be on either $HOME or $USER_LUSTRE."
      echo >&2 "(Current target: ${!var} )"
    }
    _all_safe=0
  }
done
for var in "${_on_user_lustre_only[@]}"; do
  [[ ${!var} == $USER_LUSTRE/* ]] || {
    ((_ewtrc_verbose)) && {
      echo >&2 "ERROR: $var must be on $USER_LUSTRE."
      echo >&2 "(Current target: ${!var} )"
    }
    _all_safe=0
  }
done
((_all_safe)) || return 4

for var in "${_on_user_lustre_or_home[@]}" "${_on_user_lustre_only[@]}"; do
  export "${var?}"
done

[[ $PATH =~ $EWT_HOME/tools ]] || export PATH=$EWT_HOME/tools:$PATH

# FIXME:  This should be a function definition that uses a script in
#           $EWT_HOME/tools to resolve the research programme string.
# NOTE:   Users who belong to multiple groups must pass the desired
#           RESEARCH_PROGRAMME string for a head job-style run via the -v option
#           to qsub (or the corresponding #PBS line in the job script).
source "$EWT_HOME"/src/research_programme_handling.bash
[[ -v RESEARCH_PROGRAMME ]] || set_research_programme -p -q >/dev/null 2>&1

# FIXME:  This should not be set to false for interactive runs; i.e., when the
#           user starts an interactive PBS job and runs nextflow themselves.
export NXF_ANSI_LOG='false'

# This is actually just a call to `module use` that prepends the appropriate
#   directory (which houses the nextflow module, among others) to MODULEPATH.
module load chpc/BIOMODULES
module load nextflow chpc/singularity 2>/dev/null

### Compute node-only
[[ $(hostname) =~ cnode[0-9]+ ]] && {
  export NXF_OFFLINE='true'
  return
}

### Other nodes
export NXF_DISABLE_CHECK_LATEST='true'

# Run `less` with ANSI colors support (used in nextflow log files) by default.
# alias less="less -R"

source "$EWT_HOME"/src/tless.bash

# Prevents $HOME from leaking into nextflow's singularity auto mounts via $PWD.
alias cd="cd -P"

export SINGULARITY_DISABLE_CACHE='true'
