#!/usr/bin/env bash
#
# Sets up the user's environment to run EPI2ME workflows on the CHPC.
#
# To perform said setup, source this script; e.g., issue this command:
#     source /absolute/path/to/ewtrc
# To have it performed at login, add said command (or equivalent) to your
#   $HOME/.bashrc file (at your own risk; typically to the end of it).
#
# Only the values of the EWT_HOME and NXF_{HOME,WORK,SINGULARITY_CACHEDIR}
#   environment variables are respected if already set, though said values must
#   still each point to a location on an appropriate filesystem.

_ewtrc_derive_dirname() {
  local full_path
  full_path="$(realpath "$1" 2>/dev/null)" || {
    ((_EWTRC_VERBOSE)) && echo >&2 "ERROR: Unable to resolve realpath for $1."
    return 3
  }
  echo "${full_path%/*}"
}

_ewtrc_constrain_paths() {
  local {pathy,check,constraint}_var var_fail fail
  local -a check_vars constraint_vars
  read -ra check_vars <<<"$1"
  shift
  read -ra constraint_vars <<<"$@"
  ((${#check_vars[@]} * ${#constraint_vars[@]})) || return
  for pathy_var in "${check_vars[@]}" "${constraint_vars[@]}"; do
    [[ ${!pathy_var} == /* ]] || {
      ((_EWTRC_VERBOSE)) && echo >&2 "ERROR: $pathy_var not an absolute path."
      return 3
    }
  done
  for constraint_var in "${constraint_vars[@]}"; do
    [[ -d ${!constraint_var} ]] || {
      ((_EWTRC_VERBOSE)) && echo >&2 "ERROR: $constraint_var not a directory."
      return 4
    }
  done
  for check_var in "${check_vars[@]}"; do
    for constraint_var in "${constraint_vars[@]}"; do
      [[ ${!check_var} == ${!constraint_var}/* ]] || var_fail=1
    done
    ((var_fail)) && {
      echo >&2 "ERROR: $check_var must be on one of:"
      for constraint_var in "${constraint_vars[@]}"; do
        echo >&2 "${!constraint_var}"
      done
      echo >&2 "(Current target: ${!check_var} )"
      fail=1
    }
    unset var_fail
  done
  ((fail)) && return 5
}

ewtrc_cleanup() {
  unset -v fail user_lustre_{only,or_home}
  unset -f ewtrc_cleanup
}

user_lustre_only=(NXF_WORK NXF_SINGULARITY_CACHEDIR)
user_lustre_or_home=(EWT_HOME NXF_HOME)

[[ -v PBS_ENVIRONMENT || ! $- =~ 'i' ]] && _EWTRC_VERBOSE=0 || _EWTRC_VERBOSE=1
export _EWTRC_VERBOSE

[[ ${BASH_SOURCE[0]} != "$0" ]] || {
  ((_EWTRC_VERBOSE)) && echo >&2 "ERROR: ${BASH_SOURCE[0]} can only be sourced."
  exit 1
}

# NOTE:   The trap unset part must happen in the global scope; it cannot happen
#           inside a function (i.e., it cannot happen inside ewtrc_cleanup).
# NOTE:   This trap must be unset (via `trap - RETURN`) before any source calls
#           beyond this point, and reset by a copy of this line once said calls
#           are out of the way.
trap 'ewtrc_cleanup; trap - RETURN' RETURN

[[ -v EWT_HOME ]] || EWT_HOME=$(_ewtrc_derive_dirname "${BASH_SOURCE[0]}") || {
  ((_EWTRC_VERBOSE)) && echo >&2 'ERROR: Unable to resolve EWT_HOME.'
  unset EWT_HOME
  return 3
}

trap - RETURN
source "$EWT_HOME"/src/tless.bash
source "$EWT_HOME"/src/research_programme_handling.bash
trap 'ewtrc_cleanup; trap - RETURN' RETURN

export USER_LUSTRE=/mnt/lustre/users/$USER

# NOTE:   The fallbacks for NXF_{WORK,SING*} are on lustre to protect $HOME from
#           heavy I/O loads.
# NB:     This fallback for NXF_WORK should not be treated as a default!
#           None of the tools that this package provides are designed to use
#           a monolithic NXF_WORK directory like this.
: "${NXF_HOME:=$HOME/.nextflow}"
: "${NXF_WORK:=$USER_LUSTRE/nextflow_work}"
: "${NXF_SINGULARITY_CACHEDIR:=$USER_LUSTRE/singularity_cache}"

_ewtrc_constrain_paths "${user_lustre_only[*]}" USER_LUSTRE || fail=1
_ewtrc_constrain_paths "${user_lustre_or_home[*]}" USER_LUSTRE HOME || fail=1
((fail)) && return 4

export "${user_lustre_only[@]}" "${user_lustre_or_home[@]}"

[[ $PATH =~ $EWT_HOME/tools ]] || export PATH=$EWT_HOME/tools:$PATH

# FIXME:  This should be a function definition that uses a script in
#           $EWT_HOME/tools to resolve the research programme string.
# NOTE:   Users who belong to multiple groups must pass the desired
#           RESEARCH_PROGRAMME string for a head job-style run via the -v option
#           to qsub (or the corresponding #PBS line in the job script).
[[ -v RESEARCH_PROGRAMME ]] || set_research_programme -p -q >/dev/null 2>&1

# FIXME:  This should not be set to false for interactive runs; i.e., when the
#           user starts an interactive PBS job and runs nextflow themselves.
export NXF_ANSI_LOG='false'

# This is actually just a call to `module use` that prepends the appropriate
#   directory (which houses the nextflow module, among others) to MODULEPATH.
module load chpc/BIOMODULES
module load nextflow chpc/singularity 2>/dev/null

### Compute node-only
[[ $(hostname) =~ cnode[0-9]+ ]] && {
  export NXF_OFFLINE='true'
  return
}

### Other nodes
export NXF_DISABLE_CHECK_LATEST='true'

# Run `less` with ANSI colors support (used in nextflow log files) by default.
# alias less="less -R"

# Prevents $HOME from leaking into nextflow's singularity auto mounts via $PWD.
alias cd='cd -P'

export SINGULARITY_DISABLE_CACHE='true'
