#!/usr/bin/env bash

declare -F _ewtrc_loaded_ok &>/dev/null && $_ || exit 2

source "$EWT_HOME/src/wrapping/tools.bash"
source "$EWT_HOME/src/wrapping/wrappers.bash"

(($# >= 1)) || exit 3
base_script="$1"
shift
read -ra wrappers <<<"$@"

[[ " ${wrappers[*]} " != *" _w_shebang "* ]] && wrappers+=(_w_shebang)

declare -F "${wrappers[@]}" &>/dev/null || exit 4

declare -a tmps
trap 'rm "${tmps[@]}"' EXIT
until ((${#tmps[@]} == 2)); do
  tmps+=("$(mktemp --tmpdir -q ewt_tmp_XXXXXX.bash)") || exit 5
done

cat "$base_script" | _ewt_regularise_job_script >"${tmps[0]}"
for wrapper in "${wrappers[@]}"; do
  $wrapper <"${tmps[0 - idx_offset]}" >"${tmps[1 - idx_offset]}"
  ((idx_offset ? idx_offset-- : idx_offset++))
done

cat "${tmps[0 - idx_offset]}" | _ewt_consolidate_variable_lists
