#!/usr/bin/env bash
#
# Derives a site-specfic config via qstat.

_strats=('terminate' 'finish' 'ignore' 'retry')

_default_maxRetries=5

if (($# <= 1)); then
  echo >&2 "ERROR: Too many arguments; expected at most one."
  exit 1
fi

declare -A vals=(['errorStrategy']='retry' ['maxRetries']=$_default_maxRetries)
set -- "${1,,}" "$1"
case $1 in
'') : ;;
'^[0-9]+$') vals['maxRetries']=$1 ;;
'^[a-z]+$') vals['errorStrategy']=$1 ;;
*) echo >&2 "ERROR: Could not parse \$1; got: $2" ;;
esac
if ! [[ " ${_strats[*]} " == *" ${vals['errorStrategy']} "* ]]; then
  echo >&2 "ERROR: Bad errorStrategy; must be one of: ${_strats[*]}"
  exit 2
fi

while IFS=':' read -r var val; do
  vals[$var]=$val
done < <(_ewt_queue_stats 'serial')

_vars_used=('max_queued' 'max_walltime')
_derived_vars=${!vals[*]}
for var in "${_vars_used[@]}"; do
  [[ " $_derived_vars " == *" $var "* ]] || missing_vars+=("$var")
done
if [[ -v missing_vars ]]; then
  echo >&2 "ERROR: Missing vals for: ${missing_vars[*]}"
  exit 4
fi

[[ -v NXF_HOME && -n $NXF_HOME ]] || exit 5
cat >"$NXF_HOME/config" <<-EOF
// Provides CHPC-specific nextflow configuration required to run EPI2ME Labs's
//   bioinformatics workflows.

profiles {
  singularity {
    process {
      errorStrategy = '${vals['errorStrategy']}'
      maxRetries = ${vals['maxRetries']}
    }
    // envWhitelist = "CUDA_VISIBLE_DEVICES"                   // NOTE: untested
  }

  // NOTE: The head job itself (which handles processes via qsub calls) can run
  //        on any (suitable) queue. The queue specified here controls the
  //        queue to which said head job should submit jobs.
  // NOTE: This profile is intended for use alongside the singularity profile;
  //        to use it, pass \`-p singularity,head_job\` to \`nextflow run\`.
  head_job {
    process {
      executor = 'pbspro'
      clusterOptions = "-P \${env('RESEARCH_PROGRAMME')}"
      module = ['chpc/singularity']

      // NB: When changing queue, check (or change) time and queueSize.
      queue = 'serial'
      time = ${vals['max_walltime']}.h
    }
    executor.\$pbspro.queueSize = ${vals['max_queued']}
  }
}
EOF
